version: '3.9'
services:

  postgres:
    container_name: dogker-postgres
    image: postgres:14-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'dogker' # awalnya postgres
    networks:
      - dogker
    ports:
      - 5432:5432

  pg-admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    networks:
      - dogker
    ports:
      - 5050:5050


  rabbitmq:
    image: rabbitmq:3.13.1-management
    container_name: rabbitmq
    networks:
      - dogker
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq


  container-service:
    container_name: container-service
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 300mb
    cpus: 0.5
    networks:
      - dogker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8888
    env_file:
      - .env 
# 
  dkron:
    image: dkron/dkron:3.2.7
    container_name: dkron
    networks:
      - dogker
    ports:
      - 9911:8080
    command: agent --server --bootstrap-expect=1 z--node-name=node1


volumes:
  pg-data:

networks:
  dogker:
    external: true


