// Code generated by hertz generator.

package main

import (
	pb "dogker/lintang/container-service/kitex_gen/container-service/pb/containerservice"
	"log"
	"net"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/kitex/pkg/transmeta"
	kitexServer "github.com/cloudwego/kitex/server"
)

func main() {
	h := server.Default()
	addr, _ := net.ResolveTCPAddr("tcp", "127.0.0.1:6000")
	var opts []kitexServer.Option
	opts = append(opts, kitexServer.WithMetaHandler(transmeta.ServerHTTP2Handler))
	opts = append(opts, kitexServer.WithServiceAddr(addr))
	svr := pb.NewServer(new(ContainerServiceImpl), opts...) // kitex rpc server
	go func() {
		err := svr.Run()
		if err != nil {
			log.Fatal(err)
		}
	}()
	register(h)
	h.Spin()
}
